server:
  port: 8081

hydra:
  admin_url: http://127.0.0.1:4445
  public_url: http://127.0.0.1:4444
  redirect_uri: http://127.0.0.1:8081/main.html
  client_id: auth-code-client1
  client_secret: secret
  client_scope:
    ReadAccountsBasic,
    ReadAccountsDetail,
    ReadBalances,
    ReadTransactionsBasic,
    ReadTransactionsDebits,
    ReadTransactionsDetail

obp:
  base_url:
    http://127.0.0.1:8080